### PR TITLE
Ивойлов, 853503, лаб. 2.1 (каркас).

### PR DESCRIPTION
**Pull request by am-moving-lightspeed**

### CODE REVIEW

**Comment by am-moving-lightspeed** [comment]
https://www.figma.com/file/bo9Nf6YnQm6cUehgTNteyY/Untitled?node-id=4%3A47

**Review by gmltA — CHANGES_REQUESTED** [review]
image

Is it ok that I don't see any bg? If so, I can't understand what stands behind these blocks, thus I can't figure out if you used them properly. Please, clarify that.

**Comment by am-moving-lightspeed** [comment]
image

Here are some screenshots from the game itself.
Guess, I'm going to stick to the same layouts as on the screenshots, but i might minorly change them later if I need.
The first screenshot is related to the mock you left in your comment (stage of forming player's deck of cards), the other one is related to this (game process):

image

* In-game layout is actually a bit different: action buttons from the top-right corner (on the screenshot) were 'flattened' and placed at the top, as well as the ones in the bottom-right corner were placed at the bottom of the page.
* And there are buttons now at the bottom-right of the mock you have left in your comment.

There is also an 'about' page, that is simply going to consist of an 'About' header, some rules and a back-button.

**Review by gmltA — COMMENTED** [review]
Okay. That's a <kbd>8</kbd>. Tell me if you are ok with that.

**Comment by am-moving-lightspeed** [comment]
> Okay. That's a 8. Tell me if you are ok with that.

I am

**Review by gmltA — APPROVED** [review]

**Pull request merged**
